#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Plots

Created on Thu Aug 15 14:28:24 2024

@author: gabbyhuckabee
"""

"""
Plots for energy density, temperature, entropy density
"""

import constants as c
import entropy_solver as s
from matplotlib import pyplot as plt
import numpy as np
import os

script_dir = os.path.dirname(__file__)
figs_dir = os.path.join(script_dir, 'figs/')
if not os.path.isdir(figs_dir):
    os.makedirs(figs_dir)

"""
Early Universe
"""

fig, ax = plt.subplots(1,1)
# ax.plot(np.log10(early_a),np.log10(standardmodel_preqcd[0][4][1]+standardmodel_postqcd[0][4][1]), c='#0EAD69', label='Top')
# ax.plot(np.log10(early_a),np.log10(standardmodel_preqcd[1][4][1]+standardmodel_postqcd[4][4][1]), c='#EE4266', label="Bottom")
# ax.plot(np.log10(early_a),np.log10(standardmodel_preqcd[2][4][1]+standardmodel_postqcd[6][4][1]), c='#FFD23F', label='Charm')
# ax.plot(np.log10(early_a),np.log10(standardmodel_preqcd[3][4][1]),c='#50E1BF', label="Strange")
# ax.plot(np.log10(early_a),np.log10(standardmodel_preqcd[4][4][1]), c='#8B1EB3', label="Down")
# ax.plot(np.log10(early_a), np.log10(standardmodel_preqcd[5][4][1]), c='#000000', label="Up")
# ax.plot(np.log10(early_a), np.log10(standardmodel_preqcd[6][4][1]), label="Gluon")
# ax.plot(np.log10(early_a), np.log10(standardmodel_preqcd[7][4][1]+standardmodel_postqcd[5][4][1]), label="Tau")
# ax.plot(np.log10(early_a), np.log10(standardmodel_preqcd[8][4][1]+standardmodel_postqcd[9][4][1]), label="Muon")
ax.plot(np.log10(s.early_a), np.log10(s.ea.standardmodel_preqcd[9][4][0]+s.ea.standardmodel_postqcd[-2][4][0]), label="Electron")
ax.plot(np.log10(s.early_a), np.log10(s.ea.standardmodel_preqcd[10][4][0]+s.ea.standardmodel_postqcd[-3][4][0]), label="Neutrinos")
# ax.plot(np.log10(early_a), np.log10(standardmodel_preqcd[11][4][1]+standardmodel_postqcd[3][4][1]), label="W Boson")
# ax.plot(np.log10(early_a), np.log10(standardmodel_preqcd[12][4][1]+standardmodel_postqcd[2][4][1]), label="Z Boson")
ax.plot(np.log10(s.early_a), np.log10(s.ea.standardmodel_preqcd[13][4][0]+s.ea.standardmodel_postqcd[-1][4][0]), label="Photon")
#ax.plot(np.log10(early_a), np.log10(standardmodel_preqcd[14][4][1]+standardmodel_postqcd[1][4][1]), label="Higgs")
ax.plot(np.log10(s.early_a), np.log10(s.ea.standardmodel_postqcd[-6][4][0]), label="Charged Pions")
ax.plot(np.log10(s.early_a), np.log10(s.ea.standardmodel_postqcd[-5][4][0]), label="Pi0")
ax.plot(np.log10(s.early_a), np.log10(s.ea.early_proton), label='Protons')
ax.plot(np.log10(s.early_a), np.log10(s.ea.early_neutron), label='Neutrons')
ax.plot(np.log10(s.early_a), np.log10(s.ea.early_dm), label='Dark Matter')
ax.plot(np.log10(s.early_a), np.log10(s.eps_rel), label='Relativistic')
ax.plot(np.log10(s.early_a), np.log10(s.total_bm), linestyle='dotted', label="All Fermions")
ax.axvline(x=np.log10(s.a_qcd), c='#0EAD69', linestyle='dotted', label='QCD')
ax.set_xlabel("Scale Factor")
ax.set_ylabel(r'Energy Density J/m$^3$')
ax.set_ylim(-25, 50)
ax.set_title("Log-Log Energy Density vs Scale Factor")
ax.legend()
fig.set_size_inches(9, 5)
# fig.savefig('early.eps', bbox_inches='tight')

figa, axa = plt.subplots(1,1)  
axa.plot(np.log10(s.early_a), np.log10(s.eps_rel), label='Relativistic')
axa.plot(np.log10(s.early_a), np.log10(s.total_m), label="All Matter")
axa.axvline(x=np.log10(1/(1+c.zeq)), linestyle='dotted', label='Matter-Radiation Equality')
axa.axvline(x=np.log10(s.a_qcd), c='#0EAD69', linestyle='dotted', label='QCD')
axa.set_xlabel("Scale Factor")
axa.set_ylabel(r'Energy Density J/m$^3$')
#axa.set_ylim(0, 2.33)
#axa.set_xlim(-3.9, -3.4)
axa.set_title("Matter versus Radiation")
axa.legend()
figa.set_size_inches(9, 5)
figa.savefig('mattervradiation.eps', bbox_inches='tight')

figc, axc = plt.subplots(1,1)  
axc.plot(np.log10(s.early_a), np.log10(s.eps_rel), label='Relativistic')
axc.plot(np.log10(s.early_a), np.log10(s.ea.standardmodel_preqcd[13][4][0]+s.ea.standardmodel_postqcd[-1][4][0]), label="Photon")
axc.plot(np.log10(s.early_a), np.log10(s.total_m), label="All Matter")
axc.axvline(x=np.log10(1/(1+c.zeq)), linestyle='dotted', label='Matter-Radiation Equality')
axc.set_xlabel("Scale Factor")
axc.set_ylabel(r'Energy Density J/m$^3$')
axc.set_ylim(-2.5, 5)
axc.set_xlim(-4.25, -2.75)
axc.set_title("Matter-Radiation Equality Check")
axc.legend()
figc.set_size_inches(9, 5)
figc.savefig('earlycheck.eps', bbox_inches='tight')

figd, axd = plt.subplots(1,1)  
axd.plot(np.log10(s.early_a), np.log10(s.ea.standardmodel_preqcd[-6][4][0]/c.me+s.ea.standardmodel_postqcd[-2][4][0]/c.me), label="Electrons")
axd.plot(np.log10(s.early_a), np.log10(s.ea.early_proton/c.mp), label="Protons")
#axd.axvline(x=np.log10(1/(1+zeq)), linestyle='dotted', label='Matter-Radiation Equality')
axd.set_xlabel("Scale Factor")
axd.set_ylabel(r'Number Density #/m$^3$')
axd.set_ylim(0, 75)
#axd.set_xlim(-4.25, -2.75)
axd.set_title("Charge Neutrality Check")
axd.legend()
figd.set_size_inches(9, 5)
figd.savefig('earlychargeneutrality.eps', bbox_inches='tight')

figs, axs = plt.subplots(1,1)  
axs.plot(np.log10(s.early_a), np.log10(s.s_rel), label='Relativistic')
# axs.plot(np.log10(early_a),np.log10(standardmodel_preqcd[0][4][1]+standardmodel_postqcd[0][4][1]), c='#0EAD69', label='Top')
# axs.plot(np.log10(early_a),np.log10(standardmodel_preqcd[1][4][1]+standardmodel_postqcd[4][4][1]), c='#EE4266', label="Bottom")
# axs.plot(np.log10(early_a),np.log10(standardmodel_preqcd[2][4][1]+standardmodel_postqcd[6][4][1]), c='#FFD23F', label='Charm')
# axs.plot(np.log10(early_a),np.log10(standardmodel_preqcd[3][4][1]),c='#50E1BF', label="Strange")
# axs.plot(np.log10(early_a),np.log10(standardmodel_preqcd[4][4][1]), c='#8B1EB3', label="Down")
# axs.plot(np.log10(early_a), np.log10(standardmodel_preqcd[5][4][1]), c='#000000', label="Up")
# axs.plot(np.log10(early_a), np.log10(standardmodel_preqcd[6][4][1]), label="Gluon")
# axs.plot(np.log10(early_a), np.log10(standardmodel_preqcd[7][4][1]+standardmodel_postqcd[5][4][1]), label="Tau")
# axs.plot(np.log10(early_a), np.log10(standardmodel_preqcd[8][4][1]+standardmodel_postqcd[9][4][1]), label="Muon")
#axs.plot(np.log10(early_a), np.log10(standardmodel_preqcd[9][4][2]+standardmodel_postqcd[-2][4][2]), label="Electron")
axs.plot(np.log10(s.early_a), np.log10(s.ea.standardmodel_preqcd[10][4][2]+s.ea.standardmodel_postqcd[-3][4][2]), label="Neutrinos")
# axs.plot(np.log10(early_a), np.log10(standardmodel_preqcd[11][4][1]+standardmodel_postqcd[3][4][1]), label="W Boson")
# axs.plot(np.log10(early_a), np.log10(standardmodel_preqcd[12][4][1]+standardmodel_postqcd[2][4][1]), label="Z Boson")
axs.plot(np.log10(s.early_a), np.log10(s.ea.standardmodel_preqcd[13][4][2]+s.ea.standardmodel_postqcd[-1][4][2]), label="Photon")
axs.fill_between(np.log10(s.early_a), np.log10(s.early_pbh0[:1000]), np.log10(s.early_pbh1[:1000]), label="PBHs (f=1)",  facecolor="#DCF6FF")
axs.plot(np.log10(s.early_a), np.log10(s.early_pbh2[:1000]), label="Largest PBH (f=0.3)")
axs.plot(np.log10(s.early_a), np.log10(s.early_pbh4[:1000]), label="Evaporated PBH example")
axs.plot(np.log10(s.early_a), np.log10(s.hawking4[:1000]), label="Evaporated PBH radiation")
#axs.plot(np.log10(early_a), np.log10(standardmodel_preqcd[14][4][1]+standardmodel_postqcd[1][4][1]), label="Higgs")
#axs.plot(np.log10(early_a), np.log10(standardmodel_postqcd[-6][4][2]), label="Charged Pions")
#axs.plot(np.log10(early_a), np.log10(standardmodel_postqcd[-5][4][2]), label="Pi0")
#axs.plot(np.log10(early_a), np.log10(early_s_proton), label='Protons')
#axs.plot(np.log10(early_a), np.log10(early_s_neutron), label='Neutrons')
axs.plot(np.log10(s.early_a), np.log10(s.ea.early_s_baryon+s.ea.early_s_proton+s.ea.early_s_neutron), linestyle='dotted', label="Baryons")
axs.axvline(x=np.log10(s.a_qcd), c='#0EAD69', linestyle='dotted', label='QCD')
axs.set_xlabel("Scale Factor")
axs.set_ylabel(r'Entropy Density')
axs.set_ylim(-25, 50)
axs.set_title("Log-Log Entropy Density vs Scale Factor")
axs.legend()
figs.set_size_inches(9, 5)
figs.savefig('earlys.eps', bbox_inches='tight')

figb, axb, = plt.subplots(1,1)
axb.plot(np.log10(s.early_a), np.log10(s.ea.early_proton), label='Protons')
axb.plot(np.log10(s.early_a), np.log10(s.ea.early_neutron), linestyle='dashed', label='Neutrons')
axb.plot(np.log10(s.early_a), np.log10(s.ea.early_hydrogen), label='Hydrogen')
axb.plot(np.log10(s.early_a), np.log10(s.ea.standardmodel_preqcd[-2][4][0]+s.ea.standardmodel_postqcd[-2][4][0]), label='Electrons')
#axb.plot(np.log10(early_a), np.log10(total_bm), label="All Fermions (-p and n)")
axb.axvline(x=np.log10(s.a_qcd), c='#0EAD69', linestyle='dotted', label='QCD')
axb.axvline(x=np.log10(s.a_edec), c='r', linestyle='dotted', label='Electron Decoupling')
axb.axvline(x=np.log10(s.early_a[943]), c='r', linestyle='dotted', label='Recombination')
axb.set_ylim(-10,40)
axb.set_xlabel("Scale Factor")
axb.set_ylabel(r'Energy Density J/m$^3$')
axb.set_title("Log-Log Energy Density vs Scale Factor")
axb.legend()
figb.savefig('earlybm.eps', bbox_inches='tight')

# figr, axr, = plt.subplots(1,1)
# axr.plot(np.log10(early_a), np.log10(npratio(earlytemp/10**6)), label='Theoretical Ratio')
# axr.plot(np.log10(early_a), np.log10((early_neutron/mn)/(early_proton/mp)), label='Calculated Ratio from Code')
# axr.axvline(x=np.log10(a_qcd), c='#0EAD69', linestyle='dotted', label='QCD')
# axr.set_xlabel("Scale Factor")
# axr.set_ylabel(r'$n_n/n_p$')
# axr.set_xlim(-13,-9.4)
# axr.set_ylim(-0.5,0.01)
# axr.set_title("Log-Log Neutron to Proton Ration vs Scale Factor")
# axr.legend()
# figr.savefig('earlyratio.eps', bbox_inches='tight')

# figmu, axmu, = plt.subplots(1,1)
# axmu.plot(np.log10(earlytemp), np.log10(early_mup), label=r'$\mu_p$')
# axmu.plot(np.log10(earlytemp), np.log10(early_mun), label=r'$\mu_n$')
# #axmu.axvline(x=np.log10(a_qcd), c='#0EAD69', linestyle='dotted', label='QCD')
# axmu.set_xlabel("Temperature [MeV]")
# axmu.set_ylabel(r'$\mu$ [MeV]')
# # axmu.set_xlim(-13,-9.4)
# # axmu.set_ylim(-0.5,0.01)
# axmu.set_title("Log-Log $\mu$ vs Temperature")
# axmu.legend()
# figmu.savefig('earlymu.eps', bbox_inches='tight')


# figpbh, axpbh = plt.subplots(1,1)
# #axpbh.fill_between(np.log10(totala), np.log10(early_pbh0), np.log10(early_pbh1), label="PBHs (f=1)",  facecolor="#DCF6FF")
# axpbh.plot(np.log10(totala), np.log10(early_pbh2), label="Largest PBH (f=0.3)")
# axpbh.plot(np.log10(totala), np.log10(early_pbh4), label="Evaporated PBH example")
# axpbh.plot(np.log10(totala), np.log10(hawking4), label="Evaporated PBH radiation")
# axpbh.set_xlabel("Scale Factor")
# axpbh.set_ylabel(r'Entropy Density')
# axpbh.set_ylim(-25, 50)
# axpbh.set_title("Log-Log PBH Entropy Density vs Scale Factor")
# axpbh.legend()
# figpbh.set_size_inches(9, 5)
# figpbh.savefig('pbhevap.eps', bbox_inches='tight')

"""
Late Universe
"""

#Energy Density    
fig1, ax1 = plt.subplots(1,1)  
fig1.set_size_inches(18.5, 10.5)
ax1.plot(np.log10(s.a),np.log10(s.eps_bm), c='#0EAD69', label='Baryonic Matter')
ax1.plot(np.log10(s.a),np.log10(s.eps_cmb), c='#EE4266', label="CMB")
ax1.plot(np.log10(s.a),np.log10(s.eps_nu), c='#FFD23F', label=r'$\nu_{\mathrm{primordial}}$')
ax1.plot(np.log10(s.a),np.log10(s.eps_str),c='#50E1BF', label="Stars")
ax1.plot(np.log10(s.a),np.log10(s.eps_dm), c='#8B1EB3', label="Dark Matter")
ax1.plot(np.log10(s.a), np.log10(s.eps_l), c='#000000', label="Lambda")
ax1.axvline(x=np.log10(1/(1+c.zeq)), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
ax1.axvline(x=np.log10(1/(1+c.zrec)), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
ax1.axvline(x=np.log10(1/(1+c.zdec)), c='#EE4266', linestyle='dotted', label=r'Decoupling')
ax1.axvline(x=np.log10(s.a[s.z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
ax1.axvline(x=np.log10(s.a[s.strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
ax1.axvline(x=np.log10(s.a[s.lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
ax1.set_xlabel("Scale Factor")
ax1.set_ylabel(r'Energy Density J/m$^3$')
ax1.set_title("Log-Log Energy Density vs Scale Factor")
ax1.legend()
fig1.savefig(figs_dir+'energydensity.eps')  

#Temperature
fig2, ax2 = plt.subplots(1,1)    
fig2.set_size_inches(18.5, 10.5)
ax2.plot(np.log10(1/s.a-1),np.log10(s.t_bm), c='#0EAD69', label='Baryonic Matter')
ax2.plot(np.log10(1/s.a-1),np.log10(s.t_cmb), c='#EE4266', label="CMB")
ax2.plot(np.log10(1/s.a-1),np.log10(s.t_nu), c='#FFD23F', label=r'$\nu_{\mathrm{primordial}}$')
ax2.axvline(x=np.log10(c.zeq), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
ax2.axvline(x=np.log10(c.zrec), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
ax2.axvline(x=np.log10(c.zdec), c='#EE4266', linestyle='dotted', label=r'Decoupling')
ax2.axvline(x=np.log10(1/s.a[s.z30]-1), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
ax2.axvline(x=np.log10(1/s.a[s.strpeak_arg]-1), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
ax2.axvline(x=np.log10(1/s.a[s.lambdadom_arg]-1), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
ax2.set_xlabel("Redshift")
ax2.set_ylabel("Temperature (K)")
ax2.set_title("Log-Log Temperature vs Scale Factor")
ax2.legend()
fig2.savefig(figs_dir+'temperaturez.eps')

#Entropy Density
fig3, ax3 = plt.subplots(1,1) 
fig3.set_size_inches(18.5, 10.5)   
ax3.plot(np.log10(s.a),np.log10(s.s_bm), c='#0EAD69', label=r'Baryonic Matter')
ax3.plot(np.log10(s.a),np.log10(s.s_cmb), c='#EE4266', linestyle='dashed', label=r'CMB')
ax3.plot(np.log10(s.a),np.log10(s.s_nu), c='#FFD23F', label=r'$\nu_{\mathrm{primordial}}$')
#ax3.plot(np.log10(s.a),np.log10(s.eps_dm), c='c', label="Dark Matter")
#ax3.plot(np.log10(s.a), np.log10(s.eps_l), c='g', label="Lambda")
ax3.plot(np.log10(s.a),np.log10(s.s_ceh), c='#000000', label=r'CEH')
ax3.fill_between(np.log10(s.a), np.log10(s.s_ceh_h), np.log10(s.s_ceh_l), edgecolor='#FFFFFF', facecolor='#B3B3B3', linestyle='dashdot')
ax3.plot(np.log10(s.a),np.log10(s.s_smbh),c='#8B1EB3', label=r'Supermassive Black Holes')
ax3.fill_between(np.log10(s.a), np.log10(s.s_smbhlow), np.log10(s.s_smbhhigh), edgecolor='#FFFFFF', facecolor='#F2CFFF', linestyle='dashdot')
ax3.plot(np.log10(s.a),np.log10(s.s_bh),c='#50E1BF', label=r'Stellar Mass Black Holes')
#ax3.fill_between(np.log10(s.a), np.log10(s.s_bhlow), np.log10(s.s_bhhigh), edgecolor='#FFFFFF', facecolor='#BEFFF0', linestyle='dashdot')
ax3.fill_between(np.log10(s.totala[1000:]), np.log10(s.early_pbh0[1000:]), np.log10(s.early_pbh1[1000:]), label="PBHs (f=1)",  facecolor="#DCF6FF")
ax3.plot(np.log10(s.totala[1000:]), np.log10(s.early_pbh2[1000:]), label="Largest PBH (f=0.3)")
ax3.plot(np.log10(s.totala[1000:]), np.log10(s.early_pbh4[1000:]), label=r"Evaporating PBH ($M=5\times 10^{-20} M_{\odot}$)")
ax3.plot(np.log10(s.totala[1000:]), np.log10(s.hawking4[1000:]), label="Hawking Radiation", c='#FF00FF', linestyle='dashed')
#ax3.axvline(x=np.log10(1/(1+c.zeq)), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
#ax3.axvline(x=np.log10(1/(1+c.zrec)), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
#ax3.axvline(x=np.log10(1/(1+c.zdec)), c='#EE4266', linestyle='dotted', label=r'Decoupling')
ax3.axvline(x=np.log10(s.a[s.z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
ax3.axvline(x=np.log10(s.a[s.strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
ax3.axvline(x=np.log10(s.a[s.lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
ax3.set_xlabel('Scale Factor')
ax3.set_ylabel('Entropy Density')
ax3.set_title(r'Log-Log Entropy Density vs Scale Factor')
ax3.set_ylim(bottom=-22)
ax3.legend(loc=2)
fig3.savefig(figs_dir+"s_evolution.eps")
#fig3.savefig("/figs/s_evolution_noeagle.eps")

#Entropy Total
fig4, ax4 = plt.subplots(1,1)
fig4.set_size_inches(18.5, 10.5)
ax4.plot(np.log10(s.a),np.log10(s.volumeceh*s.s_bm), c='#0EAD69', label='Baryonic Matter')
ax4.plot(np.log10(s.a),np.log10(s.volumeceh*s.s_cmb), c='#EE4266', label=r'CMB')
ax4.plot(np.log10(s.a),np.log10(s.volumeceh*s.s_nu), c='#FFD23F', label=r'$\nu_{\mathrm{primordial}}$')
#ax4.plot(np.log10(s.a),np.log10(s.eps_dm), c='c', label="Dark Matter")
#ax4.plot(np.log10(s.a), np.log10(s.eps_l), c='g', label="Lambda")
ax4.plot(np.log10(s.a),np.log10(s.stot_ceh), c='#000000', label=r'CEH')
ax4.plot(np.log10(s.a),np.log10(s.volumeceh*s.s_smbh),c='#8B1EB3', label=r'Supermassive Black Holes')
ax4.plot(np.log10(s.a),np.log10(s.volumeceh*s.s_bh),c='#50E1BF', label=r'Stellar Mass Black Holes')
ax4.axvline(x=np.log10(1/(1+c.zeq)), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
ax4.axvline(x=np.log10(1/(1+c.zrec)), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
ax4.axvline(x=np.log10(1/(1+c.zdec)), c='#EE4266', linestyle='dotted', label=r'Decoupling')
ax4.axvline(x=np.log10(s.a[s.z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
ax4.axvline(x=np.log10(s.a[s.strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
ax4.axvline(x=np.log10(s.a[s.lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
ax4.set_xlabel('Scale Factor')
ax4.set_ylabel('Entropy')
ax4.set_title(r'Log-Log Entropy vs Scale Factor')
ax4.set_ylim(bottom=50)
ax4.legend(loc=2)
fig4.savefig(figs_dir+'totalentropy.eps')

#Cosmic Event Horizon
fig5, ax5 = plt.subplots(1,1)    
fig5.set_size_inches(18.5, 10.5)
ax5.plot(np.log10(s.a),np.log10(s.r_ceh), c='#8B1EB3', label="CEH")
ax5.fill_between(np.log10(s.a), np.log10(s.r_ceh_l), np.log10(s.r_ceh_h), edgecolor='#FFFFFF', facecolor='#F2CFFF', linestyle='dashdot')
ax5.plot(np.log10(s.a),np.log10(s.r_p), c='#50E1BF', label="PH")
ax5.set_xlabel("log(a)")
ax5.set_ylabel("log(R_CEH)")
ax5.legend()
ax5.set_title("Cosmic Event Horizon Radius vs Scale Factor")
fig5.savefig(figs_dir+'horizons.eps')

# inflection=0
# for i in range(len(a)-2):
#     agrad1=(a[i+1]-a[i])/(t[i+1]-t[i])
#     agrad2=(a[i+2]-a[i+1])/(t[i+2]-t[i+1])
#     if (agrad2>agrad1)==True:
#         inflection=i+1
#         pass

# #Time vs Scale Factor
# fig6, ax6 = plt.subplots(1,1)    
# fig6.set_size_inches(18.5, 10.5)
# ax6.plot(((t/(10**9*yr))),(a))
# #ax6.axvline(x=t[zeq_arg]/(10**9*yr), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
# #ax6.axvline(x=t[zrec_arg]/(10**9*yr), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
# #ax6.axvline(x=t[zdec_arg]/(10**9*yr), c='#EE4266', linestyle='dotted', label=r'Decoupling')
# ax6.axvline(x=t[z30]/(10**9*yr), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
# ax6.axvline(x=t[strpeak_arg]/(10**9*yr), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
# ax6.axvline(x=t[lambdadom_arg]/(10**9*yr), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
# ax6.set_xlabel("Proper Time (Gyr)")
# ax6.set_ylabel("Scale Factor")
# ax6.set_title("Scale Factor vs Age")
# ax6.legend()
# fig6.savefig('scalefactor.eps')

# #Entropy (conformal volume)
# fig7, ax7 = plt.subplots(1,1) 
# fig7.set_size_inches(18.5, 10.5)   
# ax7.plot(np.log10(a),np.log10(s_bm*a**3), c='#0EAD69', label=r'Baryonic Matter')
# ax7.plot(np.log10(a),np.log10(s_cmb*a**3), c='#EE4266', linestyle='dashed', label=r'CMB')
# ax7.plot(np.log10(a),np.log10(s_nu*a**3), c='#FFD23F', label=r'$\nu_{\mathrm{primordial}}$')
# #ax7.plot(np.log10(a),np.log10(eps_dm), c='c', label="Dark Matter")
# #ax7.plot(np.log10(a), np.log10(eps_l), c='g', label="Lambda")
# ax7.plot(np.log10(a),np.log10(stot_ceh), c='#000000', label=r'CEH')
# #ax7.fill_between(np.log10(a), np.log10(s_ceh_h), np.log10(s_ceh_l), edgecolor='#FFFFFF', facecolor='#B3B3B3', linestyle='dashdot')
# ax7.plot(np.log10(a),np.log10(s_smbh*a**3),c='#8B1EB3', label=r'Supermassive Black Holes')
# #ax7.fill_between(np.log10(a), np.log10(s_smbhlow), np.log10(s_smbhhigh), edgecolor='#FFFFFF', facecolor='#F2CFFF', linestyle='dashdot')
# ax7.plot(np.log10(a),np.log10(s_bh*a**3),c='#50E1BF', label=r'Stellar Mass Black Holes')
# #ax7.fill_between(np.log10(a), np.log10(s_bhlow), np.log10(s_bhhigh), edgecolor='#FFFFFF', facecolor='#BEFFF0', linestyle='dashdot')
# ax7.axvline(x=np.log10(1/(1+zeq)), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
# ax7.axvline(x=np.log10(1/(1+zrec)), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
# ax7.axvline(x=np.log10(1/(1+zdec)), c='#EE4266', linestyle='dotted', label=r'Decoupling')
# ax7.axvline(x=np.log10(a[z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
# ax7.axvline(x=np.log10(a[strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
# ax7.axvline(x=np.log10(a[lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
# ax7.set_xlabel('Scale Factor')
# ax7.set_ylabel('Entropy Density')
# ax7.set_title(r'Log-Log Conformal Volume Entropy vs Scale Factor')
# ax7.set_ylim(bottom=-26)
# ax7.legend(loc=2)
# fig7.savefig("conformals_evolution.eps")

# #BH Zoom
# fig8, ax8 = plt.subplots(1,1) 
# fig8.set_size_inches(18.5, 10.5)   
# #ax8.plot(np.log10(a[z30:]),np.log10(s_bm[z30:]), c='#0EAD69', label=r'Baryonic Matter')
# ax8.plot(np.log10(a[z30:]),np.log10(s_cmb[z30:]), c='#EE4266', linestyle='dashed', label=r'CMB')
# ax8.plot(np.log10(a[z30:]),np.log10(s_nu[z30:]), c='#FFD23F', label=r'$\nu_{\mathrm{primordial}}$')
# #ax3.plot(np.log10(a),np.log10(eps_dm), c='c', label="Dark Matter")
# #ax3.plot(np.log10(a), np.log10(eps_l), c='g', label="Lambda")
# #ax8.plot(np.log10(a),np.log10(s_ceh), c='#000000', label=r'CEH')
# #ax8.fill_between(np.log10(a), np.log10(s_ceh_h), np.log10(s_ceh_l), edgecolor='#FFFFFF', facecolor='#B3B3B3', linestyle='dashdot')
# ax8.plot(np.log10(a[z30:]),np.log10(s_smbh[z30:]),c='#8B1EB3', label=r'Supermassive Black Holes')
# ax8.fill_between(np.log10(a[z30:]), np.log10(s_smbhlow[z30:]), np.log10(s_smbhhigh[z30:]), edgecolor='#FFFFFF', facecolor='#F2CFFF', linestyle='dashdot')
# ax8.plot(np.log10(a[z30:]),np.log10(s_bh[z30:]),c='#50E1BF', label=r'Stellar Mass Black Holes')
# ax8.fill_between(np.log10(a[z30:]), np.log10(s_bhlow[z30:]), np.log10(s_bhhigh[z30:]), edgecolor='#FFFFFF', facecolor='#BEFFF0', linestyle='dashdot')
# ax8.axvline(x=np.log10(a[z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
# ax8.axvline(x=np.log10(a[strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
# ax8.axvline(x=np.log10(a[lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
# ax8.set_xlabel('Scale Factor')
# ax8.set_ylabel('Entropy Density')
# ax8.set_title(r'Log-Log Entropy Density vs Scale Factor')
# ax8.set_ylim(bottom=-17, top=5)
# #ax8.set_xlim(left=a[z30])
# ax8.legend(loc=2)
# fig8.savefig("bh_zoom.eps")

# #Star zoom
# fig9, ax9 = plt.subplots(1,1) 
# fig9.set_size_inches(18.5, 10.5)   
# ax9.plot(np.log10(a[z30:]),np.log10(eps_bm[z30:]), c='#0EAD69', label='Baryonic Matter')
# ax9.plot(np.log10(a[z30:]),np.log10(eps_cmb[z30:]), c='#EE4266', label="CMB")
# ax9.plot(np.log10(a[z30:]),np.log10(eps_nu[z30:]), c='#FFD23F', label=r'$\nu_{\mathrm{primordial}}$')
# ax9.plot(np.log10(a[z30:]),np.log10(eps_str[z30:]),c='#50E1BF', label="Stars")
# ax9.plot(np.log10(a[z30:]),np.log10(eps_dm[z30:]), c='#8B1EB3', label="Dark Matter")
# ax9.plot(np.log10(a[z30:]), np.log10(eps_l[z30:]), c='#000000', label="Lambda")
# ax9.axvline(x=np.log10(a[z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
# ax9.axvline(x=np.log10(a[strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
# ax9.axvline(x=np.log10(a[lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
# ax9.set_xlabel("Scale Factor")
# ax9.set_ylabel(r'Energy Density J/m$^3$')
# ax9.set_title("Log-Log Energy Density vs Scale Factor")
# ax9.legend()
# #ax9.set_ylim(bottom=-17, top=5)
# #ax9.set_xlim(left=a[z30])
# fig9.savefig("star_zoom.eps")

# #Entropy (conformal volume)
# stotconformal=(s_bm+s_cmb+s_nu+s_smbh+s_bh)*a**3+stot_ceh
# fig10, ax10 = plt.subplots(1,1) 
# fig10.set_size_inches(18.5, 10.5)   
# ax10.plot(np.log10(a),np.log10(stotconformal))
# ax10.axvline(x=np.log10(1/(1+zeq)), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
# ax10.axvline(x=np.log10(1/(1+zrec)), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
# ax10.axvline(x=np.log10(1/(1+zdec)), c='#EE4266', linestyle='dotted', label=r'Decoupling')
# ax10.axvline(x=np.log10(a[z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
# ax10.axvline(x=np.log10(a[strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
# ax10.axvline(x=np.log10(a[lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
# ax10.set_xlabel('Scale Factor')
# ax10.set_ylabel('Total Entropy')
# ax10.set_title(r'Log-Log Summed Conformal Volume Entropy vs Scale Factor')
# #ax10.set_ylim(bottom=-26)
# ax10.legend()
# fig10.savefig("summedconformals_evolution.eps")

# #Entropy (CEH volume)
# stotceh=(s_bm+s_cmb+s_nu+s_smbh+s_bh)*volumeceh+stot_ceh
# fig11, ax11 = plt.subplots(1,1) 
# fig11.set_size_inches(18.5, 10.5)   
# ax11.plot(np.log10(a),np.log10(stotceh))
# ax11.axvline(x=np.log10(1/(1+zeq)), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
# ax11.axvline(x=np.log10(1/(1+zrec)), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
# ax11.axvline(x=np.log10(1/(1+zdec)), c='#EE4266', linestyle='dotted', label=r'Decoupling')
# ax11.axvline(x=np.log10(a[z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
# ax11.axvline(x=np.log10(a[strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
# ax11.axvline(x=np.log10(a[lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
# ax11.set_xlabel('Scale Factor')
# ax11.set_ylabel('Total Entropy')
# ax11.set_title(r'Log-Log Summed CEH Volume Entropy vs Scale Factor')
# #ax10.set_ylim(bottom=-26)
# ax11.legend()
# fig11.savefig("summedcehs_evolution.eps")

# #Entropy Density total
# stot_dens=(s_bm+s_cmb+s_nu+s_smbh+s_bh)+s_ceh
# fig11, ax11 = plt.subplots(1,1) 
# fig11.set_size_inches(18.5, 10.5)   
# ax11.plot(np.log10(a),np.log10(stot_dens))
# ax11.axvline(x=np.log10(1/(1+zeq)), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
# ax11.axvline(x=np.log10(1/(1+zrec)), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
# ax11.axvline(x=np.log10(1/(1+zdec)), c='#EE4266', linestyle='dotted', label=r'Decoupling')
# ax11.axvline(x=np.log10(a[z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
# ax11.axvline(x=np.log10(a[strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
# ax11.axvline(x=np.log10(a[lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
# ax11.set_xlabel('Scale Factor')
# ax11.set_ylabel('Total Entropy')
# ax11.set_title(r'Log-Log Summed Entropy Density vs Scale Factor')
# #ax10.set_ylim(bottom=-26)
# ax11.legend()
# fig11.savefig("summedsdens_evolution.eps")

# #Entropy Density total minus CEH
# stot_densnoceh=(s_bm+s_cmb+s_nu+s_smbh+s_bh)
# fig12, ax12 = plt.subplots(1,1) 
# fig12.set_size_inches(18.5, 10.5)   
# ax12.plot(np.log10(a),np.log10(stot_densnoceh))
# ax12.axvline(x=np.log10(1/(1+zeq)), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
# ax12.axvline(x=np.log10(1/(1+zrec)), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
# ax12.axvline(x=np.log10(1/(1+zdec)), c='#EE4266', linestyle='dotted', label=r'Decoupling')
# ax12.axvline(x=np.log10(a[z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
# ax12.axvline(x=np.log10(a[strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
# ax12.axvline(x=np.log10(a[lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
# ax12.set_xlabel('Scale Factor')
# ax12.set_ylabel('Total Entropy')
# ax12.set_title(r'Log-Log Summed Entropy Density (No CEH) vs Scale Factor')
# #ax10.set_ylim(bottom=-26)
# ax12.legend()
# fig12.savefig("summedsdensnoceh_evolution.eps")

# #Entropy in conformal volume minus CEH
# stot_conformalnoceh=(s_bm+s_cmb+s_nu+s_smbh+s_bh)*a**3
# fig13, ax13 = plt.subplots(1,1) 
# fig13.set_size_inches(18.5, 10.5)   
# ax13.plot(np.log10(a),np.log10(stot_conformalnoceh))
# ax13.axvline(x=np.log10(1/(1+zeq)), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
# ax13.axvline(x=np.log10(1/(1+zrec)), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
# ax13.axvline(x=np.log10(1/(1+zdec)), c='#EE4266', linestyle='dotted', label=r'Decoupling')
# ax13.axvline(x=np.log10(a[z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
# ax13.axvline(x=np.log10(a[strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
# ax13.axvline(x=np.log10(a[lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
# ax13.set_xlabel('Scale Factor')
# ax13.set_ylabel('Total Entropy')
# ax13.set_title(r'Log-Log Summed Entropy (Conformal Volume, No CEH) vs Scale Factor')
# #ax10.set_ylim(bottom=-26)
# ax13.legend()
# fig13.savefig("summedsconformalnoceh_evolution.eps")

# #Entropy in conformal volume minus CEH
# stot_nocehvolceh=(s_bm+s_cmb+s_nu+s_smbh+s_bh)*volumeceh
# fig14, ax14 = plt.subplots(1,1) 
# fig14.set_size_inches(18.5, 10.5)   
# ax14.plot(np.log10(a),np.log10(stot_nocehvolceh))
# ax14.axvline(x=np.log10(1/(1+zeq)), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
# ax14.axvline(x=np.log10(1/(1+zrec)), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
# ax14.axvline(x=np.log10(1/(1+zdec)), c='#EE4266', linestyle='dotted', label=r'Decoupling')
# ax14.axvline(x=np.log10(a[z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
# ax14.axvline(x=np.log10(a[strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
# ax14.axvline(x=np.log10(a[lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
# ax14.set_xlabel('Scale Factor')
# ax14.set_ylabel('Total Entropy')
# ax14.set_title(r'Log-Log Summed Entropy (CEH Volume, No CEH) vs Scale Factor')
# #ax10.set_ylim(bottom=-26)
# ax14.legend()
# fig14.savefig("summedsnocehvolceh_evolution.eps")

# #s_bm[z20:]=np.interp(a[z20:], np.flip(bma), np.flip(bm_eagleresults))*kb

# fig15, ax15 = plt.subplots(1,1) 
# fig15.set_size_inches(18.5, 10.5)   
# ax15.plot(np.log10(a[(z20):]),np.log10(s_bm[(z20):]), c='#0EAD69', label=r'Baryonic Matter')
# #ax15.plot(np.log10(a[(z20-10):]),np.log10(s_cmb[(z20-10):]), c='#EE4266', linestyle='dashed', label=r'CMB')
# #ax15.plot(np.log10(a[(z20-10):]),np.log10(s_nu[(z20-10):]), c='#FFD23F', label=r'$\nu_{\mathrm{primordial}}$')
# #ax3.plot(np.log10(a),np.log10(eps_dm), c='c', label="Dark Matter")
# #ax3.plot(np.log10(a), np.log10(eps_l), c='g', label="Lambda")
# #ax15.plot(np.log10(a[(z20-10):]),np.log10(s_ceh[(z20-10):]), c='#000000', label=r'CEH')
# #ax15.fill_between(np.log10(a[(z20-10):]), np.log10(s_ceh_h[(z20-10):]), np.log10(s_ceh_l[(z20-10):]), edgecolor='#FFFFFF', facecolor='#B3B3B3', linestyle='dashdot')
# #ax15.plot(np.log10(a[(z20-10):]),np.log10(s_smbh[(z20-10):]),c='#8B1EB3', label=r'Supermassive Black Holes')
# #ax15.fill_between(np.log10(a[(z20-10):]), np.log10(s_smbhlow[(z20-10):]), np.log10(s_smbhhigh[(z20-10):]), edgecolor='#FFFFFF', facecolor='#F2CFFF', linestyle='dashdot')
# #ax15.plot(np.log10(a[(z20-10):]),np.log10(s_bh[(z20-10):]),c='#50E1BF', label=r'Stellar Mass Black Holes')
# #ax15.fill_between(np.log10(a[(z20-10):]), np.log10(s_bhlow[(z20-10):]), np.log10(s_bhhigh[(z20-10):]), edgecolor='#FFFFFF', facecolor='#BEFFF0', linestyle='dashdot')
# ax15.axvline(x=np.log10(a[strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
# ax15.axvline(x=np.log10(a[lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
# ax15.set_xlabel('Scale Factor')
# ax15.set_ylabel('Entropy Density')
# ax15.set_title(r'Log-Log Entropy Density vs Scale Factor')
# ax15.set_ylim(bottom=-21)
# ax15.legend(loc=2)
# fig15.savefig("eaglezoom.eps")


#Entropy Density
fig16, ax16 = plt.subplots(1,1) 
fig16.set_size_inches(18.5, 10.5)   
ax16.plot(np.log10(s.totala),np.log10(np.concatenate((s.ea.early_s_baryon+s.ea.early_s_proton+s.ea.early_s_neutron, s.s_bm))), c='#0EAD69', label=r'Baryonic Matter')
ax16.plot(np.log10(s.totala),np.log10(np.concatenate((s.s_rel, s.s_cmb))), c='#EE4266', linestyle='dashed', label=r'CMB')
ax16.plot(np.log10(s.totala),np.log10(np.concatenate((s.ea.standardmodel_preqcd[10][4][2]+s.ea.standardmodel_postqcd[-3][4][2],s.s_nu))), c='#FFD23F', label=r'$\nu_{\mathrm{primordial}}$')
#ax16.plot(np.log10(s.a),np.log10(eps_dm), c='c', label="Dark Matter")
#ax16.plot(np.log10(s.a), np.log10(eps_l), c='g', label="Lambda")
ax16.plot(np.log10(s.totala),np.log10(np.concatenate((s.early_s_ceh,s.s_ceh))), c='#000000', label=r'CEH')
ax16.fill_between(np.log10(s.a), np.log10(s.s_ceh_h), np.log10(s.s_ceh_l), edgecolor='#FFFFFF', facecolor='#B3B3B3', linestyle='dashdot')
ax16.plot(np.log10(s.a),np.log10(s.s_smbh),c='#8B1EB3', label=r'Supermassive Black Holes')
ax16.fill_between(np.log10(s.a), np.log10(s.s_smbhlow), np.log10(s.s_smbhhigh), edgecolor='#FFFFFF', facecolor='#F2CFFF', linestyle='dashdot')
ax16.plot(np.log10(s.a),np.log10(s.s_bh),c='#50E1BF', label=r'Stellar Mass Black Holes')
ax16.fill_between(np.log10(s.a), np.log10(s.s_bhlow), np.log10(s.s_bhhigh), edgecolor='#FFFFFF', facecolor='#BEFFF0', linestyle='dashdot')
ax16.fill_between(np.log10(s.totala), np.log10(s.early_pbh0), np.log10(s.early_pbh1), label="PBHs (f=1)",  facecolor="#DCF6FF")
ax16.plot(np.log10(s.totala), np.log10(s.early_pbh2), label="Largest PBH (f=0.3)")
ax16.plot(np.log10(s.totala), np.log10(s.early_pbh4), label=r"Evaporating PBH ($M=5\times 10^{-20} M_{\odot}$)")
ax16.plot(np.log10(s.totala), np.log10(s.hawking4), label="Hawking Radiation", c='#FF00FF', linestyle='dashed')
ax16.axvline(x=np.log10(1/(1+c.zeq)), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
ax16.axvline(x=np.log10(1/(1+c.zrec)), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
ax16.axvline(x=np.log10(1/(1+c.zdec)), c='#EE4266', linestyle='dotted', label=r'Decoupling')
ax16.axvline(x=np.log10(s.a[s.z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
ax16.axvline(x=np.log10(s.a[s.strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
ax16.axvline(x=np.log10(s.a[s.lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
ax16.set_xlabel('Scale Factor')
ax16.set_ylabel('Entropy Density')
ax16.set_title(r'Log-Log Entropy Density vs Scale Factor')
ax16.set_ylim(bottom=-22)
ax16.legend(bbox_to_anchor=(1.0, 1.0), loc='upper left')
fig16.savefig(figs_dir+"s_evolution_full.eps")

#Entropy in a conformal volume, entire time domain
fig17, ax17 = plt.subplots(1,1) 
fig17.set_size_inches(18.5, 10.5)   
ax17.plot(np.log10(s.totala),np.log10(s.totala**3*np.concatenate((s.ea.early_s_baryon+s.ea.early_s_proton+s.ea.early_s_neutron, s.s_bm))), c='#0EAD69', label=r'Baryonic Matter')
ax17.plot(np.log10(s.totala),np.log10(s.totala**3*np.concatenate((s.s_rel, s.s_cmb))), c='#EE4266', linestyle='dashed', label=r'CMB')
ax17.plot(np.log10(s.totala),np.log10(s.totala**3*np.concatenate((s.ea.standardmodel_preqcd[10][4][2]+s.ea.standardmodel_postqcd[-3][4][2],s.s_nu))), c='#FFD23F', label=r'$\nu_{\mathrm{primordial}}$')
#ax17.plot(np.log10(s.a),np.log10(eps_dm), c='c', label="Dark Matter")
#ax17.plot(np.log10(s.a), np.log10(eps_l), c='g', label="Lambda")
ax17.plot(np.log10(s.totala),np.log10(s.totala**3*np.concatenate((s.early_s_ceh,s.s_ceh))), c='#000000', label=r'CEH')
ax17.fill_between(np.log10(s.a), np.log10(s.a**3*s.s_ceh_h), np.log10(s.a**3*s.s_ceh_l), edgecolor='#FFFFFF', facecolor='#B3B3B3', linestyle='dashdot')
ax17.plot(np.log10(s.a),np.log10(s.a**3*s.s_smbh),c='#8B1EB3', label=r'Supermassive Black Holes')
ax17.fill_between(np.log10(s.a), np.log10(s.a**3*s.s_smbhlow), np.log10(s.a**3*s.s_smbhhigh), edgecolor='#FFFFFF', facecolor='#F2CFFF', linestyle='dashdot')
ax17.plot(np.log10(s.a),np.log10(s.a**3*s.s_bh),c='#50E1BF', label=r'Stellar Mass Black Holes')
ax17.fill_between(np.log10(s.a), np.log10(s.a**3*s.s_bhlow), np.log10(s.a**3*s.s_bhhigh), edgecolor='#FFFFFF', facecolor='#BEFFF0', linestyle='dashdot')
ax17.fill_between(np.log10(s.totala), np.log10(s.totala**3*s.early_pbh0), np.log10(s.totala**3*s.early_pbh1), label="PBHs (f=1)", facecolor="#DCF6FF")
ax17.plot(np.log10(s.totala), np.log10(s.totala**3*s.early_pbh2), label="Largest PBH (f=0.3)")
ax17.plot(np.log10(s.totala), np.log10(s.totala**3*s.early_pbh4), label=r"Evaporating PBH ($M=5\times 10^{-20} M_{\odot}$)")
ax17.plot(np.log10(s.totala), np.log10(s.totala**3*s.hawking4), label="Hawking Radiation", c='#FF00FF', linestyle='dashed')
ax17.plot(np.log10(s.totala), np.log10(s.totala**3*np.concatenate((np.zeros(c.early_length),s.s_bh_sicilia))))
ax17.axvline(x=np.log10(1/(1+c.zeq)), c='#000000', linestyle='dotted', label=r'Matter-Radiation Equality')
ax17.axvline(x=np.log10(1/(1+c.zrec)), c='#8B1EB3', linestyle='dotted', label=r'Recombination')
ax17.axvline(x=np.log10(1/(1+c.zdec)), c='#EE4266', linestyle='dotted', label=r'Decoupling')
ax17.axvline(x=np.log10(s.a[s.z30]), c='#FFD23F', linestyle='dotted', label=r'Cosmic Dawn')
ax17.axvline(x=np.log10(s.a[s.strpeak_arg]), c='#50E1BF', linestyle='dotted', label=r'SFR Peak')
ax17.axvline(x=np.log10(s.a[s.lambdadom_arg]), c='#0EAD69', linestyle='dotted', label=r'$\Lambda$ Domination')
ax17.set_xlabel('Scale Factor')
ax17.set_ylabel('Entropy Density')
ax17.set_title(r'Log-Log Entropy Density vs Scale Factor')
ax17.set_ylim(bottom=-25, top=25)
ax17.legend(bbox_to_anchor=(1.0, 1.0), loc='upper left')
fig17.savefig(figs_dir+"conformal_s_evolution_full.eps")


print("Present Day Entropy:  S[k] from this code (Egan & Lineweaver 2009)")
print("-------------------")
print("Cosmic Event Horizon       : %10.2E \t(2.6E+122)" % (s.s_ceh[-1]*s.volumeceh[-1]/c.kb))
print("Supermassive Black Holes   : %10.2E \t(1.2E+103)" % (s.s_smbh[-1]*s.volumeceh[-1]/c.kb))
print("Stellar Mass Black Holes   : %10.2E \t(2.2E+96)" % (s.s_bh[-1]*s.volumeceh[-1]/c.kb))
print("Cosmic Microwave Background: %10.2E \t(2.03E+88)" % (s.s_cmb[-1]*s.volumeceh[-1]/c.kb))
print("Primordial Neutrinos       : %10.2E \t(1.93E+88)" % (s.s_nu[-1]*s.volumeceh[-1]/c.kb))
print("Gas and Dust               : %10.2E \t(2.7E+80)" % (s.s_bm[-1]*s.volumeceh[-1]/c.kb))